//
// Created by Thomas Abplanalp on 08.05.25.
//

#ifndef VOLTAGE_SENSOR_H
#define VOLTAGE_SENSOR_H

#include <stdint.h>

#define ROBOKIT_VOLTAGE_CHARGE_UPPER_LIMIT 5600
#define ROBOKIT_VOLTAGE_CHARGE_LOWER_LIMIT 4800
#define ROBOKIT_VOLTAGE_CHARGE_CRITICAL_LOWER_LIMIT 4600

#endif //VOLTAGE_SENSOR_H
