@startuml
'https://plantuml.com/activity-diagram-beta
skinparam defaultTextAlignment center

|Software|
:Kdo. Kalibrierung senden;
|Firmware|
:Farbwerte der Sensorzellen zurücksetzen;
:Kdo. Vorwärts mit 50% senden;
:Farben pro Zelle einlesen und
minimum und maximum speichern
oder 500ms vertreichen lassen;
:Kdo. Anhalten senden;
|Software|
if(Konnte ein Schwellenwert\nermittelt werden?) then(JA)
	:Kdo. "Der Linie folgen";
	|Firmware|
	repeat
		:Farben Rohwerte einlesen;
		:Resultat berechnen;
		|Software|
		:Resultat in korrigierende
		Fahrkommandos umwandeln;
		|Firmware|
	repeat while (Ist FAL noch eingeschaltet?)
else(NEIN)

@enduml
