@startuml
'https://plantuml.com/activity-diagram-beta
skinparam defaultTextAlignment center

start
:Initialization of\nGPIO\nDrivers (Motor and LED)\nSensors;
:Function register;

repeat
	:Wait For Command;
	if (Is Command valid?) then(YES)
		if(Is a function registered for command?) then(YES)
			:Contact HAL;
			if (Does HAL accept command?) then (YES)
				:Forward command to HAL;
			else(NO)
				:Report Failure;
			endif
		else(NO)
		endif
	else(NO)


@enduml
