@startuml
'https://plantuml.com/use-case-diagram



package "Firmware" #LightGreen {
	(Robokit Firmware) as HAL
	(Fahr-Kommandos)
	(Sensoren)
}

package "Software" #LightBlue {
	(Benutzer Interface) as (GUI)
	(WLAN)
	(Web Server)
}

(Einschalten) as Power
(Aufstart "Boot") as Boot
(Start OS) as OS



Power --> Boot
Boot --> OS
OS -down-> (GUI) : Task Prio 5
(GUI) --> (WLAN)
(GUI) --> (Web Server)

OS --> HAL : Task Prio 0
HAL --> (Fahr-Kommandos)
HAL --> (Sensoren)
OS ..> (Sensoren) : Task Prio 3

note right of OS
FreeRTOS wird gestartet und
lädt den interner Task Manager
end note


@enduml