@startuml
'https://plantuml.com/activity-diagram-beta
skinparam defaultTextAlignment center

start
:Hardware-Module laden\nGPIO\nLED\nMotor-Treiber;
:Kommandos mit Funktionen registrieren;

repeat
	#palegreen:Auf Kommando Warten;
	note left
	Alle Kommandos werden hier
	eingeschleust.
	====
	* max <b>8</b> Kommandos pendent
	end note
	if (Ist Kommando gültig?) then(JA)
		if(Ist eine Funktion\nregistriert für Kommando?) then(JA)
			:Kontaktiere HAL;
			if (Akzeptiert HAL das Kommando?) then (JA)
				:Leite Kommando weiter an\nModul in der Hardware;
			else(NEIN)
				:Melde einen Fehler;
			endif
		else(NEIN)
		endif
	else(NEIN)

@enduml
